#
# Internal Makefile for generating docx2txt distribution package
#

NAME = docx2txt
VERSION = $(shell head -1 VERSION)
PKG=$(NAME)-$(VERSION)

PKGFILES = $(NAME).{bat,config,pl,sh} BSDmakefile Makefile WInstall.bat \
	VERSION INSTALL README COPYING ChangeLog ToDo AUTHORS

dist:
	ln -s . $(PKG)
	tar zcvf $(PKG).tgz $(addprefix $(PKG)/, $(PKGFILES));
	rm $(PKG)

.PHONY: dist
